services:
  - type: web
    name: influent_api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn influent_api:app --host 0.0.0.0 --port 1000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
